# mounts local Application Default Credentials
# more info at:
#  - https://cloud.google.com/docs/authentication/application-default-credentials
#  - https://cloud.google.com/docs/authentication/provide-credentials-adc

services:
  api:
    volumes:
      - .:/app/
      - ~/.config/gcloud:/root/.config/gcloud

  worker:
    volumes:
      - .:/app/
      - ~/.config/gcloud:/root/.config/gcloud
