#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

PORT="${PORT:=8080}"

python /app/scripts/setup_pubsub_emulator/setup.py

uvicorn --reload --host 0.0.0.0 --port ${PORT} src.app_worker:app
