name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: "install terraform-docs"
      run: >
        curl -L
        "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest
        | grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")"
        > terraform-docs.tgz
        && tar -xzf terraform-docs.tgz terraform-docs
        && chmod +x terraform-docs
        && sudo mv terraform-docs /usr/bin/
    - name: "pre-commit"
      uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507  # v3.0.0
      with:
        extra_args: --all-files --show-diff-on-failure --color always
